/* =============================================================================
   Component registry — registers every <ds-*> custom element.
   Add a new component by importing its module here.
   ============================================================================= */

import '../icons/icon.js';
import './accordion/accordion.js';
import './avatar/avatar.js';
import './badge/badge.js';
import './breadcrumb/breadcrumb.js';
import './button/button.js';
import './button-group/button-group.js';
import './calendar/calendar.js';
import './chart/chart.js';
import './checkbox/checkbox.js';
import './checkbox-group/checkbox-group.js';
import './dual-list/dual-list.js';
import './counter/counter.js';
import './data-table/data-table.js';
import './date-picker/date-picker.js';
import './time-picker/time-picker.js';
import './divider/divider.js';
import './drawer/drawer.js';
import './field-helper/field-helper.js';
import './illustration/illustration.js';
import './icon-button/icon-button.js';
import './inline-alert/inline-alert.js';
import './otp-input/otp-input.js';
import './empty-state/empty-state.js';
import './dropdown-menu/dropdown-menu.js';
import './input-select/input-select.js';
import './list/list.js';
import './confirmation-modal/confirmation-modal.js';
import './modal/modal.js';
import './popover/popover.js';
import './overlay/overlay.js';
import './tab-bar-vertical/tab-bar-vertical.js';
import './tab-bar-horizontal/tab-bar-horizontal.js';
import './tab-filter/tab-filter.js';
import './fullscreen-modal/fullscreen-modal.js';
import './sidebar-l1/sidebar-l1.js';
import './sidebar-l2/sidebar-l2.js';
import './module-rail/module-rail.js';
import './container/container.js';
import './progress-bar/progress-bar.js';
import './radio/radio.js';
import './radio-group/radio-group.js';
import './rich-text-editor/rich-text-editor.js';
import './right-pane/right-pane.js';
import './content/content.js';
import './status-indicator/status-indicator.js';
import './toggle/toggle.js';
import './tag/tag.js';
import './text-link/text-link.js';
import './tooltip/tooltip.js';
import './toast/toast.js';
import './slider/slider.js';
import './text-input/text-input.js';
import './text-area/text-area.js';
import './section-header/section-header.js';
import './scrollbar/scrollbar.js';
import './message-box/message-box.js';
import './split-button/split-button.js';
import './script-editor/script-editor.js';
import './page-header/page-header.js';
import './filter-panel/filter-panel.js';
import './criteria-filter/criteria-filter.js';
import './form-footer/form-footer.js';
import './header-nav/header-nav.js';
import './kpi-card/kpi-card.js';
import './kpi-card/kpi-breakdown.js';
import './search-field/search-field.js';
import './token-field/token-field.js';
import './description-list/description-list.js';
import './file-upload/file-upload.js';
import './card/card.js';
import './widget/widget.js';
import './stepper/stepper.js';

export { DsIcon } from '../icons/icon.js';
export { DsAccordion } from './accordion/accordion.js';
export { DsAvatar } from './avatar/avatar.js';
export { DsBadge } from './badge/badge.js';
export { DsBreadcrumb } from './breadcrumb/breadcrumb.js';
export { DsDescriptionList } from './description-list/description-list.js';
export { DsButton } from './button/button.js';
export { DsButtonGroup } from './button-group/button-group.js';
export { DsCalendar } from './calendar/calendar.js';
export { DsChart } from './chart/chart.js';
export { DsCheckbox } from './checkbox/checkbox.js';
export { DsCheckboxGroup } from './checkbox-group/checkbox-group.js';
export { DsDualList } from './dual-list/dual-list.js';
export { DsCounter } from './counter/counter.js';
export { DsDataTable } from './data-table/data-table.js';
export { DsDatePicker } from './date-picker/date-picker.js';
export { DsTimePicker } from './time-picker/time-picker.js';
export { DsDivider } from './divider/divider.js';
export { DsDrawer } from './drawer/drawer.js';
export { DsFieldHelper } from './field-helper/field-helper.js';
export { DsFileUpload } from './file-upload/file-upload.js';
export { DsIllustration } from './illustration/illustration.js';
export { DsIconButton } from './icon-button/icon-button.js';
export { DsInlineAlert } from './inline-alert/inline-alert.js';
export { DsOtpInput } from './otp-input/otp-input.js';
export { DsEmptyState } from './empty-state/empty-state.js';
export { DsDropdownMenu } from './dropdown-menu/dropdown-menu.js';
export { DsInputSelect } from './input-select/input-select.js';
export { DsList, DsListItem } from './list/list.js';
export { DsConfirmationModal } from './confirmation-modal/confirmation-modal.js';
export { DsModal } from './modal/modal.js';
export { DsPopover } from './popover/popover.js';
export { DsTabBarVertical } from './tab-bar-vertical/tab-bar-vertical.js';
export { DsTabBarHorizontal } from './tab-bar-horizontal/tab-bar-horizontal.js';
export { DsTabFilter } from './tab-filter/tab-filter.js';
export { DsFullscreenModal } from './fullscreen-modal/fullscreen-modal.js';
export { DsSidebarL1 } from './sidebar-l1/sidebar-l1.js';
export { DsSidebarL2 } from './sidebar-l2/sidebar-l2.js';
export { DsModuleRail } from './module-rail/module-rail.js';
export { DsContainer } from './container/container.js';
export { DsProgressBar } from './progress-bar/progress-bar.js';
export { DsRadio } from './radio/radio.js';
export { DsRadioGroup } from './radio-group/radio-group.js';
export { DsRichTextEditor } from './rich-text-editor/rich-text-editor.js';
export { DsRightPane } from './right-pane/right-pane.js';
export { DsStatusIndicator } from './status-indicator/status-indicator.js';
export { DsToggle } from './toggle/toggle.js';
export { DsTag } from './tag/tag.js';
export { DsTextLink } from './text-link/text-link.js';
export { DsTooltip } from './tooltip/tooltip.js';
export { DsToast } from './toast/toast.js';
export { DsToaster, toast } from './toast/toast.js';
export { DsSlider } from './slider/slider.js';
export { DsTextInput } from './text-input/text-input.js';
export { DsTextArea } from './text-area/text-area.js';
export { DsSectionHeader } from './section-header/section-header.js';
export { DsScrollbar } from './scrollbar/scrollbar.js';
export { DsMessageBox } from './message-box/message-box.js';
export { DsSplitButton } from './split-button/split-button.js';
export { DsFormFooter } from './form-footer/form-footer.js';
export { DsFilterPanel } from './filter-panel/filter-panel.js';
export { DsCriteriaFilter } from './criteria-filter/criteria-filter.js';
export { DsScriptEditor } from './script-editor/script-editor.js';
export { DsPageHeader } from './page-header/page-header.js';
export { DsHeaderNav } from './header-nav/header-nav.js';
export { DsKpiCard, DsKpiGroup } from './kpi-card/kpi-card.js';
export { DsKpiBreakdown } from './kpi-card/kpi-breakdown.js';
export { DsSearchField } from './search-field/search-field.js';
export { DsTokenField } from './token-field/token-field.js';
export { DsCard } from './card/card.js';
export { DsWidget } from './widget/widget.js';
export { DsOverlay } from './overlay/overlay.js';
export { DsStepper } from './stepper/stepper.js';
