#!/usr/bin/env node
/**
 * vendor-fonts — self-host the "Personalize → Font" families so the build stays
 * SELF-CONTAINED (no Google Fonts CDN at runtime). The vanilla shell hotlinks
 * https://fonts.googleapis.com; the webapp instead serves these locally.
 *
 * One-off generator (NOT wired into prestart): it fetches from Google Fonts and
 * writes woff2 + fonts.css into public/fonts/, which is COMMITTED. Re-run only to
 * refresh the vendored fonts.
 *
 *   families: Lato 400/500/700 · Roboto 400/500/700 · Inter 400/500/600/700 ·
 *             Poppins 400/500/600   (matches Shell.html + profile.html)
 *   subset:   latin only — the personalization fonts style the English chrome;
 *             non-latin falls back to the system stack, same as the vanilla shell.
 */
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../public/fonts');

const FAMILIES = [
  { name: 'Lato', weights: [400, 500, 700] },
  { name: 'Roboto', weights: [400, 500, 700] },
  { name: 'Inter', weights: [400, 500, 600, 700] },
  { name: 'Poppins', weights: [400, 500, 600] },
];

// A modern-browser UA so the css2 API serves woff2 (not older formats).
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

async function fetchText(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`GET ${url} → ${r.status}`);
  return r.text();
}
async function fetchBuf(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`GET ${url} → ${r.status}`);
  return Buffer.from(await r.arrayBuffer());
}

/* Split the css2 response into @font-face blocks, each preceded by a `/* subset *\/`
   comment; keep only the `latin` blocks and pull out (weight, woff2 url). */
function latinFaces(css) {
  const out = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m;
  while ((m = re.exec(css))) {
    if (m[1] !== 'latin') continue;
    const block = m[2];
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (block.match(/url\(([^)]+\.woff2)\)/) || [])[1];
    if (weight && url) out.push({ weight: Number(weight), url });
  }
  return out;
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const cssRules = [];
for (const fam of FAMILIES) {
  const api = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(fam.name)}:wght@${fam.weights.join(';')}&display=swap`;
  const css = await fetchText(api);
  const faces = latinFaces(css);
  const wanted = new Set(fam.weights);
  for (const f of faces) {
    if (!wanted.has(f.weight)) continue;
    const file = `${fam.name.toLowerCase()}-${f.weight}.woff2`;
    writeFileSync(resolve(outDir, file), await fetchBuf(f.url));
    cssRules.push(
      `@font-face {\n  font-family: '${fam.name}';\n  font-style: normal;\n  font-weight: ${f.weight};\n  font-display: swap;\n  src: url('/fonts/${file}') format('woff2');\n}`,
    );
    console.log(`[vendor-fonts] ${fam.name} ${f.weight} → ${file}`);
  }
}

const header = `/* Self-hosted personalization fonts (latin) — generated by scripts/vendor-fonts.mjs.\n   Replaces the Google Fonts CDN link so the build is self-contained. */\n\n`;
writeFileSync(resolve(outDir, 'fonts.css'), header + cssRules.join('\n\n') + '\n');
console.log(`[vendor-fonts] wrote ${cssRules.length} @font-face rules → public/fonts/fonts.css`);
